nokia-wroclaw/innovativeproject-check-room

backend/package.json, frontend/package.json
fix #3 git add is default truly behaviour, I deleted them it from hooks
=> fix #3 husky warnings

.travis.yml
Example failure: https://travis-ci.com/github/pzmarzly/innovativeproject-check-room/jobs/297777781
=> add information about Travis behavior on test failure

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/Header/Header.js, frontend/src/pages/index/Index.js, frontend/src/pages/index/Index.test.js
install react router, update vulnerable  packages (npm audit), create file structure for frontend
=> Add react router and setup file structure 

.travis.yml, docker/deploy-to-heroku.sh
Follow up to #12 .
Reference: https://docs.travis-ci.com/user/deployment/script/
=> Fix Travis deployment settings

.travis.yml
=> Run Travis & Heroku deploy once, and in correct directory

frontend/src/App.js, frontend/src/assets/styles/GlobalStyle.js, frontend/src/components/CalendarList/CalendarList.js, frontend/src/components/CalendarList/CalendarListItem/CalendarListItem.js, frontend/src/components/CalendarList/CalendarListItem/CalendarListItem_styles.js, frontend/src/components/NavBar/Hamburger/Hamburger_styles.js, frontend/src/components/NavBar/NavBar.js, frontend/src/components/RoomData/RoomData.js, frontend/src/components/RoomData/RoomData_styles.js, frontend/src/pages/Calendars/Calendars.js, frontend/src/pages/Room/Room.js, frontend/src/pages/index/Index.js, frontend/src/pages/index/Index.test.js
move PageTemplate to app
fix some styles
format code - trailing spaces
=> Refactor frontend

frontend/babel-plugin-macros.config.js, frontend/src/assets/styles/GlobalStyle.js, frontend/src/components/CalendarList/CalendarListItem/CalendarListItem_styles.js, frontend/src/components/CalendarList/CalendarList_styles.js, frontend/src/components/EventList/CalendarDay/CalendarDay.js, frontend/src/components/EventList/CalendarDay/CalendarDay_styles.js, frontend/src/components/EventList/CalendarDay/DayName/DayName.js, frontend/src/components/EventList/CalendarDay/DayName/DayName_styles.js, frontend/src/components/EventList/CalendarDay/Event/Event.js, frontend/src/components/EventList/CalendarDay/Event/Event_styles.js, frontend/src/components/EventList/EventList.js, frontend/src/components/EventList/EventList_styles.js, frontend/src/components/NavBar/Hamburger/Hamburger_styles.js, frontend/src/components/NavBar/NavBar_styles.js, frontend/src/components/RoomData/RoomData_styles.js, frontend/src/components/ToggleSwitch/ToggleSwitch.js, frontend/src/components/ToggleSwitch/ToggleSwitch_styles.js, frontend/src/pages/Room/Room.js, frontend/src/templates/PageTemplate/PageTemplate.js, frontend/src/templates/PageTemplate/PageTemplate_styles.js
=> Calendar redesign

frontend/src/components/EventList/CalendarDay/Event/Event_styles.js, frontend/src/components/EventList/EventList_styles.js
add word wrapping, so longer names won't break compact view 
add padding to EventList
=> add word wrap

backend/app/calendar-client.js, backend/package-lock.json, backend/package.json, backend/routes/index.js
I used a validation method similar to one described in #17 .
We have a TOCTOU issue when detecting overlapping (concurrent) events, I'm not sure whether we can solve it.
=> Add API for creating events

frontend/src/components/EventList/CalendarDay/CalendarDay.js, frontend/src/components/EventList/CalendarDay/CalendarDay_styles.js, frontend/src/components/ToggleSwitch/ToggleSwitch_styles.js
fix styles so allDayButton looks more like interactive part #37 
also do same on toggleButton
=> Change all day styles

frontend/src/components/EventList/CalendarDay/CalendarDay.js, frontend/src/components/EventList/CalendarDay/CalendarDay_styles.js, frontend/src/components/EventList/CalendarDay/Event/Event.js, frontend/src/components/EventList/CalendarDay/Event/EventModal/EventModal.js, frontend/src/components/EventList/CalendarDay/Event/EventModal/EventModal_styles.js, frontend/src/components/EventList/CalendarDay/Event/Event_styles.js, frontend/src/components/EventList/EventList.js, frontend/src/components/EventList/EventList_styles.js
create modal resolve #42 
hide titles on compact view resolve #41
=> Create event modal

backend/app/calendar/CalendarClient.js, backend/app/controllers/calendar/addEvent.js, backend/bin/seed-rooms.js, backend/package-lock.json, backend/package.json
It adds a new command `npm run seed-rooms`, which generates events (at most 3 for each day) for a given number of days. Example: `npm run seed-rooms -- --days 3 --room all`.
=> Example data seeding

frontend/src/services/communication/Backend.js, frontend/src/services/parsing/JsonParser.js
This PR adds `addEvent` to `Backend`'s API, and does some refactoring.
=> Prepare for event adding

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/EventList/CalendarDay/Event/Event_styles.js, frontend/src/components/QrCodeButton/QrCodeButton.js, frontend/src/components/QrCodeButton/QrCodeButton_styles.js, frontend/src/components/RoomHeader/RoomHeader.js, frontend/src/components/RoomList/RoomList.js, frontend/src/components/RoomList/RoomListItem/RoomListItem.js, frontend/src/components/RoomList/RoomListItem/RoomListItem_styles.js, frontend/src/components/ToggleSwitch/ToggleSwitch_styles.js, frontend/src/pages/QRCode/QRCode.js, frontend/src/pages/QRCode/QRCode_styles.js, frontend/src/pages/RoomDetails/RoomDetails.js, frontend/src/pages/RoomDetails/RoomDetails_styles.js, frontend/src/services/parsing/RoomMetadataDTO.js
add qr code page, and link to it in room details
update names (calendar to room in places that were not updated in #40 )
update RoomMetadataDTO, it now takes all room info, not only part of it
=> Add qr code

frontend/src/components/RoomList/RoomList.js, frontend/src/services/logic/RoomFilter.js, frontend/src/services/parsing/RoomMetadataDTO.js
Following the suggestion given in code review for #47 .
Also refactored the code to make it look less like a hack.
Also made `RoomMetadataDTO.from` more lax, hopefully allowing for more flexible API usage.
=> Extract room filter

docker/nginx.template.conf
on heroku, redirect to https, if user tries to connect with http
=> add http redirect

backend/app/controllers/calendar/addEvent.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/AddNewEventButton/AddNewEventButton.js, frontend/src/components/AddNewEventButton/AddNewEventButton_styles.js, frontend/src/components/InputField/InputField_styles.js, frontend/src/components/QrCodeButton/QrCodeButton.js, frontend/src/components/QrCodeButton/QrCodeButton_styles.js, frontend/src/components/RoomData/RoomData.js, frontend/src/components/RoomData/RoomData_styles.js, frontend/src/index.js, frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom.js, frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom_styles.js, frontend/src/pages/QRCode/QRCode.js, frontend/src/pages/RoomDetails/RoomDetails.js, frontend/src/services/communication/Backend.js
This lets us add events from the front end.
We decided to use https://ant.design/ for form UI.
=> Frontend event adding

frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom.js, frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom_styles.js
This adds validation and improves UI. Follow up to #67 .
=> use ant Form component

frontend/src/App.js, frontend/src/components/AddNewEventButton/AddNewEventButton.js, frontend/src/components/AddNewEventButton/AddNewEventButton_styles.js, frontend/src/components/QrCodeButton/QrCodeButton_styles.js, frontend/src/components/StyledFormComponents/StyledFormComponents.js, frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom.js, frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom_styles.js, frontend/src/pages/QRCode/QRCode.js, frontend/src/pages/QRCode/QRCode_styles.js, frontend/src/pages/RoomDetails/RoomDetails.js, frontend/src/pages/RoomDetails/RoomDetails_styles.js, frontend/src/pages/Rooms/Rooms.js, frontend/src/services/communication/Backend.js
Follow up to #67 and #68 .
We now display the form in a drawer (sidebar popup). It works faster, looks better, does not reload the page.
=> Improve event adding form

frontend/src/pages/QRCode/QRCode.js, frontend/src/pages/RoomDetails/RoomDetails.js, frontend/src/services/communication/Backend.js
Fixes #66 . It introduces new method in Backend.js, that uses data fetched already by listRooms.
=> Cache for longer on QR code page

frontend/src/components/RoomData/RoomData.js
=> add default room description

frontend/src/services/logic/RoomFilter.js
In response to the code review under #72 , this PR extracts the filters into separate functions.
=> Refactor RoomFilter

frontend/src/services/communication/private/Query.js
Code refactoring done in #78 broke the QR code page.
=> Hotfix: add a missing function rename to Backend.js

frontend/package-lock.json, frontend/src/components/NavBar/NavBar_styles.js, frontend/src/templates/PageTemplate/PageTemplate_styles.js
there was a problem with menu, so we decided that we don't need floating menu
=> Fix z index

frontend/src/components/NavBar/Google/MyGoogleLogin.js, frontend/src/components/RoomData/RoomData.js, frontend/src/components/RoomData/RoomData_styles.js, frontend/src/components/RoomList/RoomFilterOptions/RoomFilterOptions_styles.js, frontend/src/components/RoomList/RoomList_styles.js
- Adds visual hint between room description and location - a divider, plus different font size.
- Fixes Google auth errors not being printed correctly.
- Adjust margins on room list page.
=> Minor fixes

frontend/src/pages/AddNewEventToRoom/AddNewEventToRoom.js
Fixes #82 .
I haven't tested it, but I think it should work.
@oleks12345 please review.
=> Fix default date breakage around midnight

backend/app/auth/GoogleOAuthClient.js, backend/app/controllers/user/getOrCreateUser.js, backend/app/services/FindOrCreateUserService.js
In response to the code review under #84 .
=> Extract finding and creating users from controller

frontend/src/pages/Users/Users.js, frontend/src/services/communication/private/Auth.js
This prevents application crashes on logging out while the admin panel is mounted.
There is a possibility it also fixes other crashes that I simply haven't encountered.
=> Admin panel fixes

backend/app/calendar/CalendarClient.js, backend/app/controllers/calendar/getFreeCalendars.js, backend/app/policies/UserPolicy.js, backend/routes/api.js, frontend/src/App.js, frontend/src/assets/configs/constants.js, frontend/src/services/communication/private/Command.js, frontend/src/services/communication/private/Query.js
It probably shouldn't be a POST request, but a GET one.
=> Show free rooms: backend, work in progress

frontend/src/components/AddNewEventForm/AddNewEventForm.js, frontend/src/components/AddNewEventForm/AddNewEventForm_styles.js, frontend/src/components/NavBar/NavBar.js, frontend/src/components/NavBar/NavBar_styles.js, frontend/src/templates/PageTemplate/PageTemplate.js, frontend/src/templates/PageTemplate/PageTemplate_styles.js
This PR improves the navbar and the menu (it now closes after a navigation or an outside click). It also adds margin to the drawer, necessary after #91 .
=> Visual fixes: menu, margins

frontend/src/components/AddNewEventForm/AddNewEventForm.js, frontend/src/components/AddNewEventForm/AddNewEventForm_styles.js, frontend/src/components/AddNewEventForm/NearbyRooms/NearbyRoom/NearbyRoom.js, frontend/src/components/AddNewEventForm/NearbyRooms/NearbyRoom/NearbyRoom_styles.js, frontend/src/components/AddNewEventForm/NearbyRooms/NearbyRooms.js, frontend/src/components/AddNewEventForm/NearbyRooms/NearbyRooms_styles.js, frontend/src/pages/QRCode/QRCode.js, frontend/src/pages/QRCode/QRCode_styles.js
When there is overlapping event show nearby rooms.
+ minor UI improvements
=> Show nearby rooms

frontend/src/pages/Users/Users.js
=> set users as private route

frontend/src/App.js, frontend/src/pages/Users/Users.js, frontend/src/services/logic/ProtectedRoute.js
Replaces the method implemented from #98 by the one described in #97 .
=> Protected routes refactor

backend/app/controllers/calendar/addEvent.js, backend/app/controllers/calendar/fetchCalendar.js, backend/app/services/EventOwnerService.js, backend/schema/event-owner.js, frontend/src/components/EventList/CalendarDay/Event/Event.js, frontend/src/components/EventList/CalendarDay/Event/Event_styles.js, frontend/src/services/communication/private/Auth.js, frontend/src/services/communication/private/Fetcher.js, frontend/src/services/communication/private/Query.js
In the future, event owners should be able to edit and delete events.
=> Save event owners, highlight owned events

backend/app/calendar/CalendarClient.js, backend/app/controllers/calendar/addEvent.js, backend/app/controllers/calendar/deleteEvent.js, backend/app/services/EventOwnerService.js, backend/routes/api.js, frontend/src/components/EventList/CalendarDay/CalendarDay.js, frontend/src/components/EventList/CalendarDay/Event/Event.js, frontend/src/components/EventList/CalendarDay/Event/showModal/showModal.js, frontend/src/components/EventList/CalendarDay/Event/showModal/showModal_styles.js, frontend/src/components/EventList/EventList.js, frontend/src/pages/RoomDetails/RoomDetails.js, frontend/src/services/communication/private/Command.js
Event owners can request deletion for their events.
Once deleted, the calendar data will be refreshed.
We can choose to send emails when events are cancelled, but currently are not doing so.
=> Event authors can remove events

frontend/src/components/NavBar/NavBar.js, frontend/src/components/NavBar/NavBar_styles.js, frontend/src/components/RoomData/RoomData_styles.js, frontend/src/components/UserList/UserListItem/UserListItem.js, frontend/src/components/UserList/UserListItem/UserListItem_styles.js, frontend/src/components/UserList/UserList_styles.js
make users panel responsive, small fixes and nav refactor
=> Frontend fixes

frontend/src/components/AddNewEventForm/AddNewEventForm.js, frontend/src/pages/RoomDetails/RoomDetails.js
=> Fix refreshing calendar after event removal

backend/app/controllers/calendar/addCalendar.js, backend/app/controllers/calendar/updateCalendar.js, backend/app/services/RoomToCalendarService.js, backend/routes/api.js
This doesn't change any behavior, just refactors code.
=> Code improvements

backend/app/controllers/calendar/updateCalendar.js, backend/app/services/RoomToCalendarService.js, frontend/src/components/AdminRoomList/AdminRoomList.js, frontend/src/components/AdminRoomList/AdminRoomListItem/AdminRoomListItem.js, frontend/src/components/AdminRoomList/AdminRoomListItem/RoomUpdatingModal/RoomUpdatingModal.js, frontend/src/components/AdminRoomList/AdminRoomListItem/RoomUpdatingModal/RoomUpdatingModal_styles.js, frontend/src/components/AdminRoomList/RoomCreationModal/RoomCreationModal.js, frontend/src/components/AdminRoomList/RoomCreationModal/RoomCreationModal_styles.js, frontend/src/components/EditRoomForm/EditRoomForm.js, frontend/src/components/EditRoomForm/EditRoomForm_styles.js, frontend/src/services/communication/private/Command.js, frontend/src/services/parsing/RoomMetadataDTO.js
Admins can now create and update rooms.
=> Room editing

frontend/package-lock.json, frontend/package.json, frontend/src/pages/RoomDetails/RoomDetails.js
Allow user to switch date when viewing calendar
=> date switching

backend/app/calendar/CalendarClient.js
Participants will be notified about event creation, deletion and modification.
=> Send email notifications about event updates

frontend/src/components/NavBar/NavBar.js, frontend/src/components/NavBar/NavBar_styles.js
little fixes before demo,
when resizing, logo jumped (to left or right, depends on length of user's name) 
add auto closing to dropdown
=> Front fixes

frontend/package-lock.json, frontend/package.json, frontend/src/index.js
=> Use latin extended version of Open Sans font

frontend/src/assets/styles/GlobalStyle.js
change button primary style, to use color from theme
=> fix global styles
